# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import memory_pb2 as proto_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Write = channel.unary_unary(
                '/agentmemos.v1.MemoryService/Write',
                request_serializer=proto_dot_memory__pb2.WriteRequest.SerializeToString,
                response_deserializer=proto_dot_memory__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/agentmemos.v1.MemoryService/Read',
                request_serializer=proto_dot_memory__pb2.ReadRequest.SerializeToString,
                response_deserializer=proto_dot_memory__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/agentmemos.v1.MemoryService/Delete',
                request_serializer=proto_dot_memory__pb2.DeleteRequest.SerializeToString,
                response_deserializer=proto_dot_memory__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/agentmemos.v1.MemoryService/Rollback',
                request_serializer=proto_dot_memory__pb2.RollbackRequest.SerializeToString,
                response_deserializer=proto_dot_memory__pb2.RollbackResponse.FromString,
                _registered_method=True)
        self.Federate = channel.unary_unary(
                '/agentmemos.v1.MemoryService/Federate',
                request_serializer=proto_dot_memory__pb2.FederateRequest.SerializeToString,
                response_deserializer=proto_dot_memory__pb2.FederateResponse.FromString,
                _registered_method=True)
        self.Consolidate = channel.unary_unary(
                '/agentmemos.v1.MemoryService/Consolidate',
                request_serializer=proto_dot_memory__pb2.ConsolidateRequest.SerializeToString,
                response_deserializer=proto_dot_memory__pb2.ConsolidateResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/agentmemos.v1.MemoryService/Health',
                request_serializer=proto_dot_memory__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_memory__pb2.HealthResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────

    """

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Federate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consolidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=proto_dot_memory__pb2.WriteRequest.FromString,
                    response_serializer=proto_dot_memory__pb2.WriteResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=proto_dot_memory__pb2.ReadRequest.FromString,
                    response_serializer=proto_dot_memory__pb2.ReadResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=proto_dot_memory__pb2.DeleteRequest.FromString,
                    response_serializer=proto_dot_memory__pb2.DeleteResponse.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=proto_dot_memory__pb2.RollbackRequest.FromString,
                    response_serializer=proto_dot_memory__pb2.RollbackResponse.SerializeToString,
            ),
            'Federate': grpc.unary_unary_rpc_method_handler(
                    servicer.Federate,
                    request_deserializer=proto_dot_memory__pb2.FederateRequest.FromString,
                    response_serializer=proto_dot_memory__pb2.FederateResponse.SerializeToString,
            ),
            'Consolidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Consolidate,
                    request_deserializer=proto_dot_memory__pb2.ConsolidateRequest.FromString,
                    response_serializer=proto_dot_memory__pb2.ConsolidateResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=proto_dot_memory__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_memory__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentmemos.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentmemos.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmemos.v1.MemoryService/Write',
            proto_dot_memory__pb2.WriteRequest.SerializeToString,
            proto_dot_memory__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmemos.v1.MemoryService/Read',
            proto_dot_memory__pb2.ReadRequest.SerializeToString,
            proto_dot_memory__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmemos.v1.MemoryService/Delete',
            proto_dot_memory__pb2.DeleteRequest.SerializeToString,
            proto_dot_memory__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmemos.v1.MemoryService/Rollback',
            proto_dot_memory__pb2.RollbackRequest.SerializeToString,
            proto_dot_memory__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Federate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmemos.v1.MemoryService/Federate',
            proto_dot_memory__pb2.FederateRequest.SerializeToString,
            proto_dot_memory__pb2.FederateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consolidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmemos.v1.MemoryService/Consolidate',
            proto_dot_memory__pb2.ConsolidateRequest.SerializeToString,
            proto_dot_memory__pb2.ConsolidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmemos.v1.MemoryService/Health',
            proto_dot_memory__pb2.HealthRequest.SerializeToString,
            proto_dot_memory__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
